[package]
name = "serdelekDb"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.39.2", features = ["full"] }
serde = { version = "1.0.207", features = ["derive"] }
rmp-serde = "1.0"